import { Inter } from "next/font/google";
import Head from 'next/head';
import Script from 'next/script';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Script src="/socket.io/socket.io.js"/> */}
      <Head>
        <title>Chat Application</title>
        <meta name="description" content="A simple chat application" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
